on: workflow_dispatch
name: build website
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build web --dart-define AWS_REGION=${{ europe-west2-a }} --dart-define IMAGE_URL=${{ https://blog-assets.hootsuite.com/wp-content/uploads/2022/03/free-stock-photo-sites-2-620x414.jpg }}
    # setup gcloud
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ ci-tomvandercruyssen }}
          export_default_credentials: true
    
    # Build docker image
    - name: Build docker image
      run:  docker build -t eu.gcr.io/${{ ci-tomvandercruyssen }}/flutterapp:$GITHUB_SHA .
    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: gcloud auth configure-docker -q

    # Push image to Google Container Registry
    - name: Push docker image to GCR
      run: docker push eu.gcr.io/${{ ci-tomvandercruyssen }}/flutterapp:$GITHUB_SHA
